title: Liz Wachter # your name (or website title) here
logo: "/images/1623691443235.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst
  <br><br>
  Machine Learning Portfolio 
  <br><br>
  <a href="https://www.linkedin.com/in/liz-wachter/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
